# Generated by Django 3.2.2 on 2021-05-27 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0004_auto_20210527_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_date',
        ),
    ]
